version: '3.6'
  
services:
  app:
    build:
      context: '.'
      dockerfile: 'dockerfile'
      labels:
        - "apps.cse-341-w05-prove.type=PHP"
    working_dir: '/var/www/html'
    env_file:
      - '.env'
    volumes:
      - '.:/var/www/html'
    ports: 
      - "8181:80"